# Shell variables
#     Generated by 'xtheme'

# black
color0="#3b383d"
# red
color1="#822330"
# green
color2="#68515D"
# yellow
color3="#AB4F54"
# blue
color4="#8A7C7F"
# magenta
color5="#BB908D"
# cyan
color6="#CDB6A3"
# white
color7="#C5C4C5"
