# Shell variables
#     Generated by 'xtheme'

# black
color0="#39373D"
# red
color1="#864F4C"
# green
color2="#4A5C54"
# yellow
color3="#A68D68"
# blue
color4="#607880"
# magenta
color5="#716482"
# cyan
color6="#47766C"
# white
color7="#949493"
