# Shell variables
#     Generated by 'xtheme'

# black
color0="#2F2E2C"
# red
color1="#A26666"
# green
color2="#90A57E"
# yellow
color3="#D6AF86"
# blue
color4="#7FA5BC"
# magenta
color5="#C79FC4"
# cyan
color6="#8ADAB3"
# white
color7="#D0D0D0"
