# Shell variables
#     Generated by 'xtheme'

background="#f7f7f7"    # gtk3.background.background-color
foreground="#323232"    # gtk3.background.color
# black
color0="#ffffff"        # gtk3.view>text.background-color
color8="#ffffff"        # color0 +20
# green
color2="#F0544C"        # gtk3.selection.background-color
color10="#ff5951"       # color2 +15
# white
color7="#4d4d4d"        # foreground +10
color15="#666666"       # color7 +...
