# Shell variables
#     Generated by 'xtheme'

background="#f7f7f7"    # gtk3.background.background-color
foreground="#2b2f3b"    # gtk3.background.color
# black
color0="#ffffff"        # gtk3.view>text.background-color
color8="#ffffff"        # color0 +20
# green
color2="#3498db"        # gtk3.selection.background-color
color10="#3db1ff"       # color2 +15
# white
color7="#3d4354"        # foreground +10
color15="#50576e"       # color7 +...
