# Shell variables
#     Generated by 'xtheme'

# black
color0="#343945"
# red
color1="#917070"
# green
color2="#798183"
# yellow
color3="#82817E"
# blue
color4="#6D6E75"
# magenta
color5="#96858D"
# cyan
color6="#949AA9"
# white
color7="#E5E9F0"
