# Shell variables
#     Generated by 'xtheme'

# black
color0="#000000"
# red
color1="#cc0000"
# green
color2="#4e9a06"
# yellow
color3="#c4a000"
# blue
color4="#3465a4"
# magenta
color5="#75507b"
# cyan
color6="#06989a"
# white
color7="#d3d7cf"
