# Shell variables
#     Generated by 'xtheme'

# black
color0="#282a2e"
# red
color1="#a54242"
# green
color2="#8c9440"
# yellow
color3="#de935f"
# blue
color4="#5f819d"
# magenta
color5="#85678f"
# cyan
color6="#5e8d87"
# white
color7="#707880"
