# Shell variables
#     Generated by 'xtheme'

background="#222222"    # gtk3.background.background-color
foreground="#bfbfbf"    # gtk3.background.color
# black
color0="#262626"        # gtk3.view.background-color
color8="#595959"        # color0 +20
# green
color2="#97bb72"        # gtk3.selection.background-color
color10="#bfed91"       # color2 +20
# white
color7="#d9d9d9"        # foreground +10
color15="#f2f2f2"       # color7 +...
