# Shell variables
#     Generated by 'xtheme'

background="#f7f7f7"    # gtk3.background.background-color
foreground="#273134"    # gtk3.background.color
# black
color0="#ffffff"        # gtk3.view>text.background-color
color8="#ffffff"        # color0 +20
# green
color2="#2eb398"        # gtk3.selection.background-color
color10="#38d9b8"       # color2 +15
# white
color7="#39484d"        # foreground +10
color15="#4c5f66"       # color7 +...
