# Shell variables
#     Generated by 'xtheme'

background="#1b1d24"    # gtk3.background.background-color
foreground="#bbc3c8"    # gtk3.background.color
# black
color0="#22252c"        # gtk3.view>text.background-color
color8="#494f5e"        # color0 +20
# green
color2="#3498db"        # gtk3.selection.background-color
color10="#3db1ff"       # color2 +15
# white
color7="#d2dbe0"        # foreground +10
color15="#ffffff"       # color7 +...
