# Shell variables
#     Generated by 'xtheme'

# black
color0="#343945"
# red
color1="#713F3F"
# green
color2="#6D4C4C"
# yellow
color3="#8D4F5A"
# blue
color4="#515D73"
# magenta
color5="#774B5F"
# cyan
color6="#A4A2AA"
# white
color7="#E5E9F0"
