# Shell variables
#     Generated by 'xtheme'

# black
color0="#343945"
# red
color1="#917070"
# green
color2="#709173"
# yellow
color3="#919070"
# blue
color4="#707491"
# magenta
color5="#91708F"
# cyan
color6="#709190"
# white
color7="#E5E9F0"
