# Shell variables
#     Generated by 'xtheme'

background="#1b2224"    # gtk3.background.background-color
foreground="#ccd7d4"    # gtk3.background.color
# black
color0="#222b2e"        # gtk3.view>text.background-color
color8="#485B61"        # color0 +20
# green
color2="#2eb398"        # gtk3.selection.background-color
color10="#38d9b8"       # color2 +15
# white
color7="#E5E9F0"        # foreground +10
color15="#FFFFFF"       # color7 +...
